"""embedding cache

Revision ID: 8c397f77a5cd
Revises: 97c35519fe7f
Create Date: 2026-08-26 21:30:39.645699

"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = '8c397f77a5cd'
down_revision: str | None = '97c35519fe7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_sha256', 'model', 'dim', name='uq_embedding_cache_key')
    )
    op.create_index(op.f('ix_embedding_cache_text_sha256'), 'embedding_cache', ['text_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_cache_text_sha256'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
