"""baseline schema

Revision ID: 97c35519fe7f
Revises: 
Create Date: 2026-08-26 20:14:23.429834

"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '97c35519fe7f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('document_version_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.Enum('answered', 'partial', 'abstained', name='verdict', native_enum=False), nullable=False),
    sa.Column('abstain_reason', sa.Text(), nullable=True),
    sa.Column('citation_coverage', sa.Float(), nullable=True),
    sa.Column('quotes_total', sa.Integer(), nullable=False),
    sa.Column('quotes_repaired', sa.Integer(), nullable=False),
    sa.Column('quotes_dropped', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('eurlex', 'ec_page', name='source_type', native_enum=False), nullable=False),
    sa.Column('eli_uri', sa.Text(), nullable=True),
    sa.Column('celex_base', sa.String(length=32), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('check_interval_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('check_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.Enum('unchanged', 'new_version', 'error', name='check_outcome', native_enum=False), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_run_source_id'), 'check_run', ['source_id'], unique=False)
    op.create_table('document_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('celex', sa.String(length=64), nullable=True),
    sa.Column('cellar_id', sa.String(length=128), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_path', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('formex', 'xhtml', 'pdf', name='doc_format', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'ingesting', 'active', 'superseded', 'failed', name='version_status', native_enum=False), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['document_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'celex', name='uq_document_version_source_celex')
    )
    op.create_index('ix_document_version_one_active', 'document_version', ['source_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_document_version_source_id'), 'document_version', ['source_id'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='run_status', native_enum=False), nullable=False),
    sa.Column('units_written', sa.Integer(), nullable=False),
    sa.Column('chunks_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_document_version_id'), 'ingestion_run', ['document_version_id'], unique=False)
    op.create_table('structural_unit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_type', sa.Enum('recital', 'chapter', 'section', 'article', 'paragraph', 'point', 'annex', name='unit_type', native_enum=False), nullable=False),
    sa.Column('unit_number', sa.String(length=32), nullable=True),
    sa.Column('unit_path', sa.String(length=255), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_normalized', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('eurlex_deeplink', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['structural_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structural_unit_document_version_id'), 'structural_unit', ['document_version_id'], unique=False)
    op.create_index('ix_structural_unit_lookup', 'structural_unit', ['document_version_id', 'unit_type', 'unit_number'], unique=False)
    op.create_index(op.f('ix_structural_unit_parent_id'), 'structural_unit', ['parent_id'], unique=False)
    op.create_index('ix_structural_unit_path', 'structural_unit', ['document_version_id', 'unit_path'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('structural_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=3072), nullable=False),
    sa.Column('embed_model', sa.String(length=64), nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structural_unit_id'], ['structural_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_document_version_id'), 'chunk', ['document_version_id'], unique=False)
    op.create_index('ix_chunk_embedding_hnsw', 'chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.create_index('ix_chunk_fts', 'chunk', ['fts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunk_structural_unit_id'), 'chunk', ['structural_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_structural_unit_id'), table_name='chunk')
    op.drop_index('ix_chunk_fts', table_name='chunk', postgresql_using='gin')
    op.drop_index('ix_chunk_embedding_hnsw', table_name='chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.drop_index(op.f('ix_chunk_document_version_id'), table_name='chunk')
    op.drop_table('chunk')
    op.drop_index('ix_structural_unit_path', table_name='structural_unit')
    op.drop_index(op.f('ix_structural_unit_parent_id'), table_name='structural_unit')
    op.drop_index('ix_structural_unit_lookup', table_name='structural_unit')
    op.drop_index(op.f('ix_structural_unit_document_version_id'), table_name='structural_unit')
    op.drop_table('structural_unit')
    op.drop_index(op.f('ix_ingestion_run_document_version_id'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_document_version_source_id'), table_name='document_version')
    op.drop_index('ix_document_version_one_active', table_name='document_version', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('document_version')
    op.drop_index(op.f('ix_check_run_source_id'), table_name='check_run')
    op.drop_table('check_run')
    op.drop_table('source')
    op.drop_table('query_log')
    # ### end Alembic commands ###
