"""Source authority tier.

Sources stop being interchangeable here. The corpus now holds the Regulation, the
Commission's guidelines and Q&A, and voluntary codes of practice, and answering "what is
legally required?" mainly out of a code of practice would be wrong however well that code
matched the question. ``authority`` is what retrieval orders evidence by and what the answer
labels its claims with.

Existing rows are the AI Act and its recitals, so backfilling to ``'law'`` is correct rather
than merely convenient -- and it is also the right default for a row inserted without one.

Revision ID: a5e81c3f0d92
Revises: e3a9c5d17b42
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "a5e81c3f0d92"
down_revision = "e3a9c5d17b42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "source",
        sa.Column("authority", sa.String(), nullable=False, server_default="law"),
    )
    # Hand-written rather than autogenerated: Alembic does not see CHECK constraints, and an
    # unrecognised tier must not be storable. Name matches Enum(name=...) verbatim.
    op.create_check_constraint(
        "authority", "source", "authority IN ('law', 'guidance', 'code')"
    )


def downgrade() -> None:
    op.drop_constraint("authority", "source", type_="check")
    op.drop_column("source", "authority")
